/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as banksimulationSol from "./Banksimulation.sol";
export type { banksimulationSol };
import type * as interfaceSol from "./Interface.sol";
export type { interfaceSol };
import type * as nftSol from "./Nft.sol";
export type { nftSol };
import type * as uniswapSol from "./Uniswap.sol";
export type { uniswapSol };
export type { IBankSimulation } from "./IBankSimulation";
export type { IERC20 } from "./IERC20";
