/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBankSimulation,
  IBankSimulationInterface,
} from "../IBankSimulation";

const _abi = [
  {
    inputs: [],
    name: "Deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "retrieveFunds",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "withDrawFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBankSimulation__factory {
  static readonly abi = _abi;
  static createInterface(): IBankSimulationInterface {
    return new utils.Interface(_abi) as IBankSimulationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBankSimulation {
    return new Contract(address, _abi, signerOrProvider) as IBankSimulation;
  }
}
