/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Nft, NftInterface } from "../../../contracts/Interface.sol/Nft";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "string",
        name: "URI",
        type: "string",
      },
    ],
    name: "mintTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Nft__factory {
  static readonly abi = _abi;
  static createInterface(): NftInterface {
    return new utils.Interface(_abi) as NftInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Nft {
    return new Contract(address, _abi, signerOrProvider) as Nft;
  }
}
